### ISSUE TITLE
你好 我使用的时候遇到这个问题 I/chromium: [INFO:CONSOLE(10)] "Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17", source: file:///android_asset/AAHighchartsLib.js (10) 请问您知道什么原因吗

### ISSUE THREAD

**Issue by tanttian** [AAChartModel/AAChartCore#13]
你好 我使用的时候遇到这个问题
I/chromium: [INFO:CONSOLE(10)] "Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17", source: file:///android_asset/AAHighchartsLib.js (10)
请问您知道什么原因吗

**Comment by AAChartModel** [comment]
The requested series type does not exist
This error happens when setting chart.type or series.type to a series type that isn't defined in Highcharts. A typical reason may be that the module or extension where the series type is defined isn't included.

For example in order to create an arearange series, the highcharts-more.js file must be loaded.


Refer to www.highcharts.com/errors/17
